### ISSUE TITLE
App crash with multiple USBs

### ISSUE THREAD

**Issue by AKuHAK** [pcm720/nhddl#10]
App crash with multiple USBs. This happens because it is exiting immediately when mass0: folder become available. However, at that point mass1 isnt mounted yet, and will mount after a bit of time. And when BDM driver mounts mass1 it will corrupt all mass0 open file/dir descriptors. I think it should be mentioned in readme, cause the only solution is to wait some period of time and check if mass1 doesnt arise unexpectedly.

https://github.com/pcm720/nhddl/blob/fe0232e88db690438956c7dc7bc0464a09d64d4e/src/iso.c#L34-L36

**Comment by pcm720** [comment]
Is there a way to check if BDM driver is ready?

**Comment by AKuHAK** [comment]
> Is there a way to check if BDM driver is ready?
> Waiting for an indeterminate amount of time seems... not ideal.

As I know its not possible, cause, for example bdm driver can mount usb device on the fly, when you insert it. I am not an expert maybe there exist some sort of callback.

**Comment by pcm720** [comment]
IMO, the driver should not corrupt actively used descriptors since something is actually using them, but oh well.
I guess I should add a warning to not plug in any USB devices after the launcher is running...

As for mass0/mass1 handling during initialization, I'm in the middle of refactoring that part.
I want NHDDL to be aware of the device it's launching from so it could keep its own directory available after IOP reset.
Obviously, it needs to handle more than one mass device for it to work.

**Comment by AKuHAK** [comment]
Yes, I already half the way into that direction in my fork. The easiest way will be to change pa2sdk driver to monut not that abstract mass%d: mountpoint but the underlying partition, like usb0p0. Unfortunately, it may require a lot of work cause mass acronym is hardcoded in too many places inside SDK.

**Comment by AKuHAK** [comment]
Neutrino also suffers from the same problem and opl too.

**Comment by AKuHAK** [comment]
> I want NHDDL to be aware of the device it's launching from so it could keep its own directory available after IOP reset.

By its current design it is not possible. When you launch your app from some filebrowser, you only can deal with argv[0]. In case of BDM driver you will get anonymous `mass%d:/path`. All information about what was the underlying BDM device is lost after IOP reset, so you have no way to know that.

**Comment by pcm720** [comment]
> When you launch your app from some filebrowser, you only can deal with argv[0]. In case of BDM driver you will get anonymous mass%d:/path. All information about what was the underlying BDM device is lost after IOP reset, so you have no way to know that

Well, I my testing I was able to get some device information from `mass%d:` mountpoint using this:
```
  char dpath[] = "massX:";
  for (char dnum = '0'; dnum < '5'; dnum++) {
    dpath[4] = dnum;
    DIR *dir = opendir(dpath);
    if (dir != NULL) {
      uint32_t devNr;
      int iop_fd = ps2sdk_get_iop_fd(dir->dd_fd);
      uint32_t drvNameI = (uint32_t)fileXioIoctl2(iop_fd, USBMASS_IOCTL_GET_DRIVERNAME, NULL, 0, NULL, 0);
      fileXioIoctl2(iop_fd, USBMASS_IOCTL_GET_DEVICE_NUMBER, NULL, 0, &devNr, 4);
      char *drvName = (char *)&drvNameI;
      printf("%s using BDM device: %s%d\n", dpath, drvName, (int)devNr);
      closedir(dir);
      continue;
    }
    // No more devices
    break;
  }
```

I haven't tested it on a real PS2 yet, but in PCSX2 I'm getting this output for ATA:
`mass0: using BDM device: ata0`
The plan was to use the drvName to determine the BDM device type.

**Comment by pcm720** [comment]
> Do you mean that this code works before IOP reset? Its strange as all the information about mountpoint should be erased from memory after calling LoadELFFromFile, but I personally never checked this. But keep in mind that as this is undocumented feature it may broke in some sdk versions.

No, that was after IOP reset and BDM modules. I haven't really checked if ULE or other loaders reset IOP before loading any ELFs. I was thinking of the case when NHDDL is launched from USB, in theory IOP should still have USB modules loaded.

> You can even merge ELF with IRX files to not depend on memory card storage

I still don't really want to do that because some modules are not available in PS2SDK, and I don't want to copy their sources from Neutrino and update them every so often.

> But keep in mind that there can be some strange behaviour

I also don't like that some modules introduce significant delays (like udpbd).
Maybe it's not the best way to do this...

> But you still need to store information about storage.

Well, not really. This approach still can work with `mass:` paths.
Most of NHDDL file handling functions are mountpoint-agnostic, just have to refactor path building functions to get mountpoint from ISO path instead of using hardcoded `mass:`.

> Don't quite understand what is wrong with mc ? As I know it does not require full path, relative paths works just fine for mc.

Some Neutrino arguments (e.g. `mc0`, `mc1`, `ata0`, `ata0id`) require full path for the file.
Since we don't really know what number the device is beforehand, the only way to pass arguments to Neutrino is to substitute `mass:/` with `mass%d:` at runtime.
Obviously NHDDL must also use an ELF loader that doesn't reset the IOP before executing `neutrino.elf`. This is something I already tried and it seems to work perfectly fine.

**Comment by AKuHAK** [comment]
> No, that was after IOP reset and BDM modules. I haven't really checked if ULE or other loaders reset IOP before loading any ELFs. I was thinking of the case when NHDDL is launched from USB, in theory IOP should still have USB modules loaded.

After module load mountpoints will be remounted, so you cannot trust them anymore. For example, you loaded NHDDL from wle mx4sio fork, where mountpoint points to mx4sio, but with multi mode it remounts mass0 as ata for example. I am not quite sure how to find out that moment, when drivers are loaded, but mountpoints still aren't.

@israpps thanks, I was thinking that it was you, and that this was a reason wle all-in-one doesn't exist.

**Comment by pcm720** [comment]
> After module load mountpoints will be remounted, so you cannot trust them anymore. For example, you loaded NHDDL from wle mx4sio fork, where mountpoint points to mx4sio, but with multi mode it remounts mass0 as ata for example. I am not quite sure how to find out that moment, when drivers are loaded, but mountpoints still aren't.

And we don't really care about mountpoints changing since we can just go through all of them and check if our own path exists on one of them. Sure, it can lead to users inadvertently loading older versions of Neutrino, but there's not a lot we can do about it.

**Comment by AKuHAK** [comment]
> Obviously NHDDL must also use an ELF loader that doesn't reset the IOP before executing `neutrino.elf`. This is something I already tried and it seems to work perfectly fine.

Yes, in that case you dont need to deal with putting neutrino modules and configs in memory card as relative path should be accessible at neutrino start.

> Some Neutrino arguments (e.g. mc0, mc1, ata0, ata0id) require full path for the file.

Ah, really? I thought that everything can use relative paths, the only problem is that path should be accessibe before bdm drivers loaded. But, yes, I didnt check it, always used full paths.

> And we don't really care about mountpoints changing since we can just go through all of them

Doh, this is hacky solution, but yes, it will work, if you hardcode for NHDDL some path inside mass for storing settings.

> I was thinking of the case when NHDDL is launched from USB, in theory IOP should still have USB modules loaded.

This one I already checked: no USB drivers are loaded after wlaunchelf starts an app, so its not an option.

> I also don't like that some modules introduce significant delays (like udpbd).

In multi fork there is also non-avoidable delay loop for checking all the existing mass mountpoints, didint measure it on real hardware though.

**Comment by pcm720** [comment]
> Ah, really? I thought that everything can use relative paths, the only problem is that path should be accessibe before bdm drivers loaded. But, yes, I didnt check it, always used full paths.

Yeah. Neutrino tries to open relative path as-is and gives up after some time.

> Doh, this is hacky solution, but yes, it will work, if you hardcode for NHDDL some path inside mass for storing settings.

Well, there's no need to hardcode anything.
NHDDL knows current working directory during initialization, so it only needs to find the path matching argv[0] (without the mountpoint).

> This one I already checked: no USB drivers are loaded after wlaunchelf starts an app, so its not an option.

Well, this basically kills the whole idea of running from USB.
At least without embedding all BDM IRXs into nhddl.elf.

**Comment by pcm720** [comment]
@AKuHAK 
> This one I already checked: no USB drivers are loaded after wlaunchelf starts an app, so its not an option.

My testing shows that wLaunchELF doesn't reset the IOP before starting ELFs, so USB modules are still there when NHDDL is launched from USB drive.
As of latest commit, NHDDL works perfectly when launched from USB drive via wLE.

**Comment by AKuHAK** [comment]
> My testing shows that wLaunchELF doesn't reset the IOP before starting ELFs, so USB modules are still there when NHDDL is launched from USB drive.\nAs of latest commit, NHDDL works perfectly when launched from USB drive via wLE.

Nice to hear, but issue was about multiple usbs crashing. Does it work now when 2 or more usbs are attached?

**Comment by pcm720** [comment]
> Nice to hear, but issue was about multiple usbs crashing.

And it was fixed by adding a note in the README and handling multiple BDM devices, yes.

> Does it work now when 2 or more usbs are attached?

It does and it doesn't. NHDDL has no issues enumerating and listing ISOs on all mass devices.

However, my testing shows that Neutrino has issues loading ISOs from USB when multiple USB devices are connected..
For some reason, I was able to launch ISO only from usb1 (passed to Neutrino as `mass1:`), trying to load anything from usb0 (as `mass0:`) always fails and returns to OSDSYS.

**Comment by AKuHAK** [comment]
Ah, yes, if nhddl now lists everything, it's ok. I will try to provide fix for neutrino as well, when I have time.

**Comment by pcm720** [comment]
> Ah, yes, if nhddl now lists everything, it's ok. I will try to provide fix for neutrino as well, when I have time.

It looks like the same thing with corrupted file descriptors you've described in this issue.
I commented out IOP reset in Neutrino and looked at debug logs:

One USB drive connected:
```
Reboot IOP into Load Environment (LE)
Block Device Manager (BDM) v1.1
BDM: connecting fs MBR
BDM: connecting fs GPT
BDM: BDM event thread running
- bdm.irx started
- iomanX.irx started
fileXio: fileXio: fileXio RPC Server v1.00
Copyright (c) 2003 adresd
- fileXio.irx started
- isofs.irx started
FreeUsbd v.0.1.2
- usbd_mini.irx started
- usbmass_bd_mini.irx started
BDM FatFs driver (FAT/exFAT) v1.4
BDM: connecting fs fatfs
- bdmfs_fatfs.irx started
Loading mass0:/image.iso...
BDM: connecting device usb0p0 id=0x0
Found MBR disk
Found partition type 0x0b
BDM: connecting device usb0p1 id=0xb
BDM: usb0p0 mounted to MBR
BDM: usb0p1 mounted to fatfs
- size = 623MiB
- media = ps2 cd
file[0] fragments: start=0, count=4
- frag[0] start=36530, count=946176
- frag[1] start=982770, count=12288
- frag[2] start=995122, count=212992
- frag[3] start=1208754, count=104512
Using BDM device: usb0
Compat flags: 0x1, IOP=0x8
<game ELF loading>
```

Two USB drives connected:
```
Reboot IOP into Load Environment (LE)
Block Device Manager (BDM) v1.1
BDM: connecting fs MBR
BDM: connecting fs GPT
BDM: BDM event thread running
- bdm.irx started
- iomanX.irx started
fileXio: fileXio: fileXio RPC Server v1.00
Copyright (c) 2003 adresd
- fileXio.irx started
- isofs.irx started
FreeUsbd v.0.1.2
- usbd_mini.irx started
- usbmass_bd_mini.irx started
BDM FatFs driver (FAT/exFAT) v1.4
BDM: connecting fs fatfs
- bdmfs_fatfs.irx started
Loading mass0:/image.iso...
BDM: connecting device usb0p0 id=0x0
Found MBR disk
Found partition type 0x0b
BDM: connecting device usb0p1 id=0xb
BDM: usb0p0 mounted to MBR
BDM: usb0p1 mounted to fatfs
BDM: connecting device usb1p0 id=0x0
- size = 0MiB
Unable to read ISO
Found MBR disk
Found partition type 0x0c
BDM: connecting device usb1p1 id=0xc
BDM: usb1p0 mounted to MBR
BDM: usb1p1 mounted to fatfs
<exit to OSDSYS>
```
