### ISSUE TITLE
Persona 3 Fes cutscenes suffer stutters compared to OPL

### ISSUE THREAD

**Issue by AmyRoxwell** [pcm720/nhddl#14]
Launching Persona 3 FES on the newest version causes all cutscenes to suffer stutters, very noticeable on the first one after you had boot the game while using a HDD.

On OPL this can be fixed by enabling MODE 2 (Synchronous Mode) but enabling any of the settings on NHDDL do nothing.

Neutrino version used: neutrino-20241103-2ccca2d8
NHDDL Version used: nhddl-v0.3.0

**Comment by pcm720** [comment]
When you enable `IOP: Sync reads` in NHDDL, it simply passes the `-gc=2` parameter to Neutrino.
NHDDL is responsible only for launching Neutrino, it doesn't affect game performance or compatibility.

Consider creating an issue in Neutrino repository instead.

**Comment by AmyRoxwell** [comment]
> When you enable `IOP: Sync reads` in NHDDL, it simply passes the `-gc=2` parameter to Neutrino. NHDDL is responsible only for launching Neutrino, it doesn't affect game performance or compatibility.
> 
> Consider creating an issue in Neutrino repository instead.

Gotcha, I didn't know where to make the report! Ty so much for the answer :D!
