### ISSUE TITLE
NHDDL fails to initialize dev9 module if console doesn't have a network adapter attached

### ISSUE THREAD

**Issue by ab310714gz4700** [pcm720/nhddl#18]
I was using a fat PS2 without network adapter installed
It worked on slim
It's related to dev9 module

**Comment by pcm720** [comment]
Yeah, sorry, but this is not an issue.
You need to provide some actual details, like
- The version you're trying to launch
- Device and application you're trying to launch NHDDL from
- Whether NHDDL is placed beside neutrino.elf

**Comment by pcm720** [comment]
Okay, now this is something I can work with.

**Comment by pcm720** [comment]
Latest nightly now should be able to launch on PS2s without a network adapter

**Comment by ab310714gz4700** [comment]
Thank you
