### ISSUE TITLE
Nhddl freezes for a single character

### ISSUE THREAD

**Issue by DukeJP** [pcm720/nhddl#19]
Using the latest version of nhddl 1.0.0, I noticed that while scrolling through my list of games, when I got to a certain page it would freeze and not respond anymore.
When I checked the excel list that OPL Manager generates, I noticed that on the page that should be showing was the game
Blood Will Tell - Tezuka Osamu’s Dororo (Undub)

And I noticed that the symbol ( ’ ) was unique in my list, when I deleted it the problem was solved
(detailed explanation of the behavior) When I got to page 6, there was no problem at all. When I pressed Right to show page 7, the one for Blood will tell, it did not show it and Nhddl freezes

I'm not actually asking for a fix, the solution is as simple as a rename, I'm just leaving this as help in case it happens to someone else

**Comment by pcm720** [comment]
> I'm not actually asking for a fix

Thanks for finding a bug. This needs to be fixed.
The idea was to skip rendering characters not present in font pages, but I obviously forgot to test if it actually does that.

I'll look into it and fix it later tonight.

**Comment by pcm720** [comment]
@DukeJP
Please test this build and report if it fixed the issue for you:
https://github.com/pcm720/nhddl/actions/runs/12355553276/artifacts/2326740721

The intended behavior is to skip characters not present in the font pages, so you should see "Blood Will Tell - Tezuka Osamus Dororo (Undub)" instead of NHDDL crashing :)

**Comment by DukeJP** [comment]
Yes, work well, and in the way you say (renamed Blood Will Tell to its original name)
