### ISSUE TITLE
Feature request: cache game list

### ISSUE THREAD

**Issue by DukeJP** [pcm720/nhddl#2]
Congratulations on the project.
I ask you for that, a way to store the list of games (and maybe an option to rescan it), because in my case, it takes more than 1 minute to load the GUI (4 terabyte disk and 1000 isos)

**Comment by pcm720** [comment]
Thanks!
Yeah, caching is something I've already been thinking about and is next on the list of things to do.

I plan to drop support for ISOs outside of the `CD` and `DVD` directories and rescan only if the last modification date changes on one of those folders.

**Comment by DukeJP** [comment]
Regarding the CD or DVD paths, the first time I used Nhddl, I got isos that I had deleted a long time ago and they were in the $RECYCLE. BIN folder which is hidden by default. It was fixed by deleting those files.

**Comment by pcm720** [comment]
@DukeJP
Can you try this binary and see if it improves consecutive scans?
[nhddl.elf.zip](https://github.com/user-attachments/files/17357657/nhddl.elf.zip)

I've yet to test it thoroughly, but it significantly speeds up the scanning in PCSX2.
Ultimately, I chose to scan all directories except for the config and ART directories, directories used by OPL and XEBPLUS for storing other files, and directories that start with `.` or `$`. 
This should fix your $RECYCLE.BIN issue while still allowing for flexible folder structure.

**Comment by DukeJP** [comment]
@pcm720   Works perfectly. After a first mandatory scan, reloading takes less than 3 seconds.
