### ISSUE TITLE
Incorrect/incomplete IRX error handling 

### ISSUE THREAD

**Issue by israpps** [pcm720/nhddl#3]
https://github.com/pcm720/nhddl/blob/2410fc32eba35ce9dadfd9d1df50334339190f09/src/module_init.c#L59

You're using SifLoadModule for loading IRX modules.

What you should do is use SifLoadStartModule, and check the additional parameter, it takes an `int*` and after function execution it returns the IRX entry point return value. Wich should be always `0` or `2`. If it is `1` means the module willingly requested to be unloaded.

The actual return value of the function corresponds to the return value of the operation. When larger than 0 it's the module ID. When negative, it corresponds to an error coming from MODLOAD.IRX

This is (and must be) applicable to SifExecModuleBuffer()

I'm making an issue instead of a PR bc I'm away from my PC for a few days

An example of a good error handling:
https://github.com/israpps/PlayStation2-Basic-BootLoader/blob/main/src/main.c#L651-L654

**Comment by pcm720** [comment]
Thanks for letting me know and for providing an example of proper error handling!
I'll fix it in a different branch and pull it into main later.
