### ISSUE TITLE
usage of `rom0:FONTM` makes nhddl incompatible with `DESR` models

### ISSUE THREAD

**Issue by israpps** [pcm720/nhddl#6]
I know DESR models are a small userbase, but this might be another incentive to switch to a TTF Font?

https://github.com/pcm720/nhddl/blob/64d5d68aa91cc15c8ab053e0cd3937725c257f6a/src/gui.c#L72

**Comment by pcm720** [comment]
Apart from it not incompatible with DESR models, I also don't like how FONTM looks.
I agree that the whole font rendering needs a rework.
It's something I'd like to do, just not sure when I'll have the time to do it.
