### ISSUE TITLE
Multi-disc games

### ISSUE THREAD

**Issue by AITUS95** [pcm720/nhddl#8]
Is it possible to change discs on the fly? For example, Dragon Ball Z Budokai Tenkaichi 3 uses an option to unlock content by inserting the discs of the first and second games.

**Comment by pcm720** [comment]
Not really.
NHDDL is just a launcher for Neutrino.
And as far as I know, Neturino can't switch ISOs on the fly (neither can OPL).

So, I suggest you use your disc copies to unlock extra content or get past the prompt if for some reason the game doesn't prompt you to save before switching the disc.
